### ISSUE TITLE
General - Convert Tables to Cards

### ISSUE THREAD

**Issue by RahulR100** [Northeastern-Electric-Racing/PM-Dashboard-v1#106]
Massive tables are not good from a user interface perspective. They show too much data and lack further functionality. Change all instances where massive tables are displayed to use cards (like how work package lookup does things). Warning: this will probably take some time.

**Comment by jamescd18** [comment]
This will be implemented with individual issues for each specific instance so as to first define what the cards should consist of or look like. See #113 for an example.
