### ISSUE TITLE
Changes - Status Update on Submit Not Working

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v1#111]
Having seen #29 closed with the merging of #93, I wanted to try it out and see how it all works. Upon thorough examining, I seem to have found that it doesn't work as expected. Tried on both Chrome and Safari to ensure it is not a browser-dependent issue. Double checked that the expected client-side JS code for this functionality was indeed being used. Let's meet and discuss how it works so we can figure out what isn't behaving how we expect it to.

Below is the situation on Safari in which the notification correctly indicates having updated the status to 25%, yet after 5 minutes the status field still displayed 0%.
<img width="1031" alt="Screen Shot 2021-01-14 at 8 59 47 PM" src="https://user-images.githubusercontent.com/51571627/104683287-75c25b00-56ab-11eb-92c6-7ff239477e70.png">

Below is the situation on Chrome with setting the status in the reverse direction. The notification correctly indicates having set the status to 0%, but the status still displays 25%.
<img width="933" alt="Screen Shot 2021-01-14 at 9 07 03 PM" src="https://user-images.githubusercontent.com/51571627/104683773-74456280-56ac-11eb-86ae-e00fc34803fe.png">

**Comment by kevinyu328** [comment]
That's weird, the feature seems to be working for me. Below is a screenshot of what happens after changing the status from 0% to 25%. There were a couple times where it was a bit glitchy, but I thought it was something to do with my internet, as it has been working fine ever since. 

<img width="1149" alt="Screen Shot 2021-01-15 at 12 22 53 PM" src="https://user-images.githubusercontent.com/59738829/104758651-badaa180-572c-11eb-9e24-d829f3b2557d.png">

**Comment by RahulR100** [comment]
It seems to work for me too. I have had to incorporate a 1 second delay to account for the google sheet updating in the background which can sometimes be glitchy. This is the easiest way to do this given the current method of database implementation (I don't know if there is a means of getting a success response from google sheets and then trigger the refresh). The latter method may be less buggy than this if it is possible to do that.

**Comment by jamescd18** [comment]
See `JavaScript.html` [line 29](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/5e1e8c8a8860769a7016b13267fbd1ecad3451f1/client-code/JavaScript.html#L29), [line 34](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/5e1e8c8a8860769a7016b13267fbd1ecad3451f1/client-code/JavaScript.html#L34), [line 130](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/5e1e8c8a8860769a7016b13267fbd1ecad3451f1/client-code/JavaScript.html#L130), and [line 167](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/5e1e8c8a8860769a7016b13267fbd1ecad3451f1/client-code/JavaScript.html#L167) for an example of re-implementing the on-success handler in order to subsequently have additional code execute.

Trying it again, it looks like it now works for me. No clue why it wasn't working before. I also just noticed the callback function which waits 1 second does not implement the loading spinner like the rest of them do as seen on [line 153](https://github.com/Northeastern-Electric-Racing/NER-PM-Dashboard/blob/5e1e8c8a8860769a7016b13267fbd1ecad3451f1/client-code/JavaScript.html#L153).

**Comment by RahulR100** [comment]
Ok, I will investigate implementing the success handler. I do not think we need to implement the loading spinner as it would take so little time to update that it would not be able to fully display the spinner.

**Comment by jamescd18** [comment]
Fantastic! With the spinner, the important part is to understand two key reasons why we have it.
1. Your internet connection speed is different from someone else's.
2. Users should know when things change.

These are two (among many) guiding principals of web development and user experience design. Connection speed (or lack of connection) is a problem many users can and do run into that makes the user experience quite different from what the developer may see when making the feature. In this case, while your connection may be fast and result in a very short spinner time, for others, the spinner may run for a whole 3-10 seconds, making it more than worthwhile. 

Additionally, not keeping the user informed about information changing runs the risk of users getting confused or disoriented, and potentially not sure why things change, or not noticing something has changed at all. It's in a similar vein to providing success and error messages to users so that they know what's going on.

As such, I think it's important that we implement the loading spinner in this small albeit important feature.

**Comment by RahulR100** [comment]
Right that makes a lot of sense. I will implement that as well
