### ISSUE TITLE
General - Remove padding from lists

### ISSUE THREAD

**Issue by RahulR100** [Northeastern-Electric-Racing/PM-Dashboard-v1#134]
Lists are naturally given some padding. However, right now this causes them to become more offset from other content such as in the Work Package lookup card. Although minor it would look a lot better without padding

**Comment by jamescd18** [comment]
Please add screenshots to help illustrate what you are talking about since this is a front-end issue. I suggest using Chrome dev tools to help distinguish which components of the styling are problematic.

**Comment by RahulR100** [comment]
Here is the state before:

<img width="1006" alt="Screenshot 2021-01-20 at 2 01 57 PM" src="https://user-images.githubusercontent.com/29384660/105222192-0dafc100-5b52-11eb-9f52-e397550f5818.png">

And after...

<img width="990" alt="Screenshot 2021-01-20 at 2 01 26 PM" src="https://user-images.githubusercontent.com/29384660/105222207-1607fc00-5b52-11eb-868d-1bd2ce036888.png">

**Comment by jamescd18** [comment]
> Here is the state before:

Is this the correct issue for these screenshots?

**Comment by RahulR100** [comment]
Ah yes I should have made it more clear and I probably should change the last image too. If you look closely at the description section you can see that the bullet points have moved. I will change the second image and highlight the change to make it clearer.

**Comment by jamescd18** [comment]
I think the after state is a little too extreme in removing the padding since it seems to defeat the purpose of having bullets. @RahulR100 could you try aligning the left edge of the bullets with the rest of the text above and posting another screenshot alongside the specific CSS change that made the change? Thank you!

**Comment by RahulR100** [comment]
Yes I also saw that modifying the ul/ol padding messed up other pages as well. I know bootstrap uses a standard 15px padding almost everywhere so that is the amount of padding that will be needed. The modified css looks like this:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/29384660/105654131-4256ac00-5eb5-11eb-8239-2e6d2a67ed4f.png">
