### ISSUE TITLE
Gantt - Make "View Full Gantt Chart" Button Display a Full-page Modal

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v1#145]
#109 removed the input group that was on the page and replaced it with a "View Full Gantt Chart" button. Currently, this button places the Gantt chart within the gray content box. However, due to the size of the gantt chart, we wish for the button to display a full-page modal of the gantt chart instead. This full-page modal of the Gantt chart was previously implemented but got removed with #109. Commit ba743f7ce079caa0b8e6b2f7d792613943beef1e should have the functionality of the full-page modal implemented if you are unsure on how to implement it.

**Comment by RahulR100** [comment]
#106 changes the way this works with `container-fluid`. Consider changing this to remove the button altogether as the full width gantt table will always be displayed by default now.
