### ISSUE TITLE
Reports - Remove Empty Cards From Manufacturing & Welding Card Set

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v1#188]
Some records in the Fab & Weld tab in the PM21 spreadsheet currently have empty rows between them. This results in empty cards as shown in the screenshot below. Please fix this issue without altering the PM21 spreadsheet and by filtering out the empty rows.

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/59738829/107887307-1be3c980-6ed3-11eb-9661-e0eb7e8082a6.png">

**Comment by jamescd18** [comment]
This can be done by checking the row and if the first item in the row is blank then assume the row is blank because the first item in the row is the Fab/Weld request ID.
