### ISSUE TITLE
Home - Dynamically Fill in Contact Details

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v1#42]
The contact section of the home page still just has placeholder values. Replace them with a programmatically generated list. The list should come from the users table.
<img width="419" alt="Screen Shot 2020-12-14 at 1 27 28 PM" src="https://user-images.githubusercontent.com/51571627/102137716-1d7c0d00-3e10-11eb-9f6c-82acd56b0221.png">

**Comment by RahulR100** [comment]
Where do I find the users table?
