### ISSUE TITLE
General - Fix HTML Table Scrollable

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v1#68]
Vertical and horizontal scrolling was introduced to handle HTML tables that are ginormous (see Reports -> Change Requests). Since then, scrollbar artifacts are now see on what appears to be all HTML tables, no matter their size. We would like to remove the scroll bars where possible and not needed. The HTML table helper function should have a parameter for dictating style attributes in a string. Examine the CSS and various other code to determine how the scrollable function is added, and why it lingers when not needed. See below for an example of not-needed scrollbars.

<img width="960" alt="Screen Shot 2021-01-02 at 10 13 44 AM" src="https://user-images.githubusercontent.com/51571627/103463728-64f50b00-4ce3-11eb-8fc6-f03cb30dff75.png">

**Comment by RahulR100** [comment]
This issue should be closed as we are moving away from tables to cards in #113
